version: "3.8"

services:
  mysqldb:
    build: ./mysql
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - main_net
  app:
    depends_on:
      - mysqldb
    build: ./spring
    restart: on-failure
    env_file: ./.env
    ports:
      - 6868:6869
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - main_net

  api-mysql:
    depends_on:
      - mysqldb
    build: ./node
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - main_net
  
  api-mongo:
    depends_on:
      - mongodb
    build: ./node2
    ports:
      - 3001:3001
    env_file:
      - .env
    networks:
      - main_net

  mongodb:
    image: mongo:4.2.3-bionic
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongodb:/data/db
    networks:
      - main_net

volumes:
  db:
  mongodb:

networks:
  main_net:
